### ISSUE TITLE
Exception during LatentDiffusion.instantiate_first_stage

### ISSUE THREAD

**Issue by zhanghe-21** [AlonzoLeeeooo/LCDG#1]
Hi @AlonzoLeeeooo,

I tried to run the training code, and encountered an error when ldm.models.autoencoder.AutoencoderKL was loading checkpoint params from pretrained first_stage_models，error detail shows below:
![image](https://github.com/AlonzoLeeeooo/LCDG/assets/139303790/1df4f8b5-6c03-465c-95a6-c950bec02338)

But when I tried debug the code, the current model showed different from the error detail above. I paste the corresponding part of the encoder model structure below:
![image](https://github.com/AlonzoLeeeooo/LCDG/assets/139303790/8cc97c28-3d6b-4a14-8494-1be180bef23b)

I tried to find other works like T2I, the didn't use checkpoint for ldm.models.autoencoder.AutoencoderKL. So I wonder if you encountered this error before, and could you give some advice concerned.
Any tips or suggetions would be great appreciated. Looking forward for your reply.

Best regards.

**Comment by AlonzoLeeeooo** [comment]
Hi @zhanghe-21,

Thank you for your attention! The `AutoencoderKL` is essentially the VQ model that Stable Diffusion requires. It seems that you were loading an incorrect version of it.  Note that we use version `2.1` as the diffusion backbone model. I suggest you refer to the official instructions in their GitHub repo and prepare all the required model weights. Also, don't forget to modify corresponding lines in the configuration file.

Best,

**Comment by haychong** [comment]
Thanks for your advice @AlonzoLeeeooo .

The reason is the wrong VQ model. I changed it to kl-f8, it works fine now. 👍

**Comment by zhanghe-21** [comment]
Thanks for your advice @AlonzoLeeeooo .

The reason is the wrong VQ model. I changed it to kl-f8, it works fine now. 👍
