### ISSUE TITLE
release window of code implementation

### ISSUE THREAD

**Issue by Njasa2k** [AlonzoLeeeooo/LCDG#2]
Hey there, just wondering if there's any word on the release window for the code implementation. Any updates on the availability of the codebase would be greatly appreciated.

**Comment by AlonzoLeeeooo** [comment]
> Hey there, just wondering if there's any word on the release window for the code implementation. Any updates on the availability of the codebase would be greatly appreciated.
> 
> 

Hi @ninjasaid2k,

Thank you for your attention! We are currently working on some other submissions, so it would be unavailable for me to work on releasing the code recently. I guess we would start updating the progress after approximately two weeks. 

Best,

**Comment by AlonzoLeeeooo** [comment]
Hi @ninjasaid2k ,

We are glad to inform you that our model weights are available on our [Huggingface repo](https://huggingface.co/AlonzoLeeeooo/LaCon/tree/main) and [ModelScope repo](https://modelscope.cn/models/AlonzoLeeeoooo/LaCon). Please feel free to download the weights and try LaCon on your ends!

If you have any further questions about our work, please do not hesitate to contact me.

Best regards
